export const enum Actions {
    FETCH_CTX_START = 'FETCH_CTX_START',
    FETCH_CTX_SUCCEED = 'FETCH_CTX_SUCCEED',
    FETCH_CTX_ERROR = 'FETCH_CTX_ERROR',

    SYNC_USER_START = 'SYNC_USER_START',
    SYNC_USER_SUCCEED = 'SYNC_USER_SUCCEED',
    SYNC_USER_ERROR = 'SYNC_USER_ERROR',

    SAVE_USER_START = 'SAVE_USER_START',
    SAVE_USER_SUCCEED = 'SAVE_USER_SUCCEED',
    SAVE_USER_ERROR = 'SAVE_USER_ERROR',

    GEN_CV_START = 'GEN_CV_START',
    GEN_CV_SUCCEED = 'GEN_CV_SUCCEED',
    GEN_CV_ERROR = 'GEN_CV_ERROR',

    SET_LOCALE = 'SET_LOCALE',
    SET_THEME = 'SET_THEME',
}
