export const enum Actions {
    FETCH_CTX_START = 'FETCH_CTX_START',
    FETCH_CTX_SUCCEED = 'FETCH_CTX_SUCCEED',
    FETCH_CTX_ERROR = 'FETCH_CTX_ERROR',

    SYNC_USER_START = 'SYNC_USER_START',
    SYNC_USER_SUCCEED = 'SYNC_USER_SUCCEED',
    SYNC_USER_ERROR = 'SYNC_USER_ERROR',

    SET_LOCALE = 'SET_LOCALE',
    SET_THEME = 'SET_THEME',
}
